2021-05-23T09:49:26|ERROR|HexSimAnalysis|HexSIM_Analysis Failed to update figure1: 'HexSimAnalysis' object has no attribute 'imvRaw'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\andrea\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\andrea\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\HexSIM_Analyser\\HexSimAnalyser_measurement.py", line 129, in update_display\n    self.imvRaw.setImage(self.imageRaw,\n', "AttributeError: 'HexSimAnalysis' object has no attribute 'imvRaw'\n"]
2021-05-23T09:49:34|ERROR|HexSimAnalysis|HexSIM_Analysis Failed to update figure1: 'HexSimAnalysis' object has no attribute 'imvRaw'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\andrea\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\andrea\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\HexSIM_Analyser\\HexSimAnalyser_measurement.py", line 129, in update_display\n    self.imvRaw.setImage(self.imageRaw,\n', "AttributeError: 'HexSimAnalysis' object has no attribute 'imvRaw'\n"]
2021-05-23T09:49:35|ERROR|HexSimAnalysis|HexSIM_Analysis Failed to update figure1: 'HexSimAnalysis' object has no attribute 'imvRaw'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\andrea\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\andrea\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\HexSIM_Analyser\\HexSimAnalyser_measurement.py", line 129, in update_display\n    self.imvRaw.setImage(self.imageRaw,\n', "AttributeError: 'HexSimAnalysis' object has no attribute 'imvRaw'\n"]
2021-05-23T09:49:36|ERROR|HexSimAnalysis|HexSIM_Analysis Failed to update figure1: 'HexSimAnalysis' object has no attribute 'imvRaw'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\andrea\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\andrea\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\HexSIM_Analyser\\HexSimAnalyser_measurement.py", line 129, in update_display\n    self.imvRaw.setImage(self.imageRaw,\n', "AttributeError: 'HexSimAnalysis' object has no attribute 'imvRaw'\n"]
2021-05-23T09:54:00|ERROR|HexSimAnalysis|HexSIM_Analysis Failed to update figure1: 'HexSimAnalysis' object has no attribute 'imvRaw'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\andrea\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\andrea\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\HexSIM_Analyser\\HexSimAnalyser_measurement.py", line 129, in update_display\n    self.imvRaw.setImage(self.imageRaw,\n', "AttributeError: 'HexSimAnalysis' object has no attribute 'imvRaw'\n"]
